version: '3.8'

services:
  # Database (PostgreSQL)
  db:
    image: postgres:15
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=iot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - iot-network

  # Ứng dụng chính (FastAPI)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/iot_db
      - API_HOST=0.0.0.0
      - API_PORT=8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  postgres_data: 